apiVersion: v1
kind: Service
metadata:
  name: events-api-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 30036
  selector:
    app: events-api